version: '3'
services:
  user-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: user_service_db
    ports:
      - "3306:3306"

  user-service-app:
    build: ./user-service/
    volumes:
      - ./user-service/:/app
    ports:
      - "8080:8080"
    depends_on:
      - user-service-db

  product-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: product_service_db
    ports:
      - "3307:3306"

  product-service-app:
    build: ./product-service/
    volumes:
      - ./product-service/:/app
    ports:
      - "8081:8080"
    depends_on:
      - product-service-db

  order-service-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: order_service_db
    ports:
      - "3308:3306"

  order-service-app:
    build: ./order-service/
    volumes:
      - ./order-service/:/app
    ports:
      - "8083:8080"
    depends_on:
      - order-service-db

  api-gateway:
    build: ./api-gateway/
    volumes:
      - ./api-gateway/:/app
    ports:
      - "8082:8080"
    depends_on:
      - user-service-app
      - product-service-app
      - order-service-app
